---
- name: check if nodejs already installed
  stat:
    path: /usr/bin/node
  register: nodejs_bin

- name: download and setup nodejs source
  shell: |
    curl -fsSL https://rpm.nodesource.com/setup_lts.x | bash -
  when: not nodejs_bin.stat.exists

- name: install latest nodejs temporary
  become: yes
  yum:
    name: nodejs
    state: present
  when: not nodejs_bin.stat.exists

- name: download and setup yarn source
  shell: |
    curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo

- name: install latest yarn temporary
  become: yes
  yum:
    name: yarn
    state: present

- name: install latest package temporary
  become: yes
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - gcc
      - clang
      - openssl-devel
      - zlib-devel
      - mysql-devel
      - readline-devel
