---
- name: check if nodejs already installed
  stat:
    path: /usr/bin/node
  register: nodejs_bin

- name: download and setup nodejs source
  shell: |
    curl -fsSL https://rpm.nodesource.com/setup_lts.x | bash -
  when: not nodejs_bin.stat.exists

- name: install latest nodejs temporary
  yum:
    name: "{{ item }}"
    state: present
  with_items: 
    - nodejs
  when: not nodejs_bin.stat.exists

- name: download and setup yarn source
  shell: |
    curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo

- name: install latest package temporary
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - clang
    - openssl-devel
    - zlib-devel
    - mysql-devel
    - yarn
    - readline-devel
    
