---
- name: check if nodejs already installed
  stat:
    path: /usr/bin/node
  register: nodejs_bin

- file:
    path: /var/cache/yum/*
    state: absent

- name: Fetch nodejs
  ansible.builtin.uri: 
    url: https://rpm.nodesource.com/setup_16.x
    return_content: yes
  register: nodejs_installer
  when: not nodejs_bin.stat.exists

- name: Run nodejs_installer
  become: yes
  ansible.builtin.shell:
    cmd: bash -
    stdin: "{{ nodejs_installer.content }}"
  when: not nodejs_bin.stat.exists

- name: install present_package
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items: 
    - gcc-c++
    - make

- name: install present nodejs
  become: yes
  yum:
    name: nodejs
    state: present
  when: not nodejs_bin.stat.exists

- name: Fetch yarn
  ansible.builtin.uri: 
    url: https://dl.yarnpkg.com/rpm/yarn.repo
    return_content: yes
  register: yarn_installer

- name: Run yarn_installer
  ansible.builtin.shell:
    cmd: tee /etc/yum.repos.d/yarn.repo
    stdin: "{{ yarn_installer.content }}"

- name: install present yarn temporary
  become: yes
  yum:
    name: yarn
    state: present

- name: install present package temporary
  become: yes
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - gcc
      - clang
      - openssl-devel
      - zlib-devel
      - mysql-devel
      - readline-devel
