---
- name: Check rbenv install
  stat:
    path: "{{ rbenv_path }}"
  register: rbenv_exists

- name: Download rbenv_ruby-build
  become: yes
  uri:
    url: https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer
    return_content: yes
  register: rbenv_installer
  when: not rbenv_exists.stat.exists

- name: Run rbenv_ruby-build
  become: yes
  shell: "{{ rbenv_installer.content }}"
  args:  
    chdir: /home/ec2-user/
  when: not rbenv_exists.stat.exists

- name: Add rbenv to PATH
  lineinfile: 
    path: /home/ec2-user/.bash_profile
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'

- name: rbenv init in ~/.bash_profile
  lineinfile: 
    path: /home/ec2-user/.bash_profile
    line: 'eval "$(rbenv init -)"'

- name: Load rbenv setting
  ansible.builtin.shell: 
    cmd: source /home/ec2-user/.bash_profile

- name: Check ruby installed
  stat: 
    path: "{{ rbenv_path }}/shims/ruby"
  register: rbenv_check_install

- name: Install Ruby
  shell: bash -lc "rbenv install {{ ruby_version }}"

- name: Set default Ruby version g
  shell: bash -lc "rbenv global {{ ruby_version }}"

- name: Set default Ruby version h
  shell: bash -lc "rbenv rehash"
