---
- name: check rbenv install
  stat:
    path: "{{ rbenv_path }}"
  register: rbenv_exists

- name: download rbenv_ruby-build
  ansible.builtin.uri:
    url: https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer
    return_content: yes
  register: rbenv_installer
  when: not rbenv_exists.stat.exists

- name: Run rbenv_ruby-build
  become: yes
  ansible.builtin.shell:
    cmd: bash
    stdin: "{{ rbenv_installer.content }}"
  when: not rbenv_exists.stat.exists

- name: Add rbenv to PATH
  lineinfile: 
    path: /home/ec2-user/.bash_profile
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'

- name: rbenv init
  ansible.builtin.shell:
    cmd: /home/ec2-user/.rbenv/bin/rbenv init

- name: Eval rbenv init in ~/.bash_profile
  lineinfile: 
    path: /home/ec2-user/.bash_profile
    line: 'eval "$(rbenv init - bash)"'

- name: Load rbenv setting
  ansible.builtin.shell: 
    cmd: source /home/ec2-user/.bash_profile

- name: Check ruby installed
  stat: 
    path: "{{ rbenv_path }}/shims/ruby"
  register: rbenv_check_install

- name: Install Ruby
  ansible.builtin.shell:
    cmd: rbenv install "{{ ruby_version }}"

- name: Set default Ruby version g
  ansible.builtin.shell: 
    cmd: rbenv global "{{ ruby_version }}"

- name: Set default Ruby version h
  ansible.builtin.shell:
    cmd: rbenv rehash
