---
- name: check rbenv install
  stat:
    path: "{{ rbenv_path }}"
  register: rbenv_exists

- name: download rbenv_ruby-build
  ansible.builtin.uri:
    url: https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer
    return_content: yes
  when: not rbenv_exists.stat.exists

- name: Add rbenv to PATH
  lineinfile: 
    path: /home/ec2-user/.bash_profile
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'

- name: rbenv init
  ansible.builtin.command:
    cmd: /home/ec2-user/.rbenv/bin/rbenv init
  args:
    warn: no
  when: not rbenv_exists.stat.exists

- name: Eval rbenv init in ~/.bash_profile
  lineinfile: 
    path: /home/ec2-user/.bash_profile
    line: 'eval "$(rbenv init -)"'

- name: Load rbenv setting
  shell: bash -lc source /home/ec2-user/.bash_profile

- name: Check ruby installed
  stat: 
    path: "{{ rbenv_path }}/shims/ruby"
  register: rbenv_check_install

- name: Install Ruby
  shell: bash -lc rbenv install "{{ ruby_version }}"
  when: rbenv_check_install.rc == 1

- name: Set default Ruby version
  shell: bash -lc rbenv global "{{ ruby_version }}" && rbenv rehash
