---
- name: Check nginx installed
  become: yes
  yum:
    name: nginx
    state: present
  register: check_nginx_installed
  ignore_errors: yes

- name: Install nginx
  become: yes
  shell: amazon-linux-extras install -y nginx1
  when: check_nginx_installed is failed

- name: Change nginx ownership
  become: yes
  file:
    path: /etc/nginx
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: Setting Nginx
  template:
    src: roles/nginx/templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: ec2-user
    group: ec2-user
