---
- hosts: TargetNode
  become: yes
  roles:
    - { role: git, tags: git }
    - { role: webpack, tags: webpack }
    - { role: mysql, tags: mysql }
    - { role: ruby, tags: ruby }
    - { role: clone, tags: clone }
    
